### ISSUE TITLE
Show error message when failing to load document

### ISSUE THREAD

**Issue by frivoal** [vivliostyle/vivliostyle-ui#13]

**Comment by satorumurmur** [comment]
redesigned. https://github.com/vivliostyle/vivliostyle-ui/commit/514008937dbd909b1d69e5dd487a6af3af088178 > @kwkbtr

**Comment by satorumurmur** [comment]
redesigned. https://github.com/vivliostyle/vivliostyle-ui/commit/514008937dbd909b1d69e5dd487a6af3af088178 + https://github.com/vivliostyle/vivliostyle-ui/commit/5350364409fbca72829feac3082eb07885a728ed + https://github.com/vivliostyle/vivliostyle-ui/commit/60deb195d586d6c80a0792ff6aedaa9e7b45c4a2 > @kwkbtr

**Comment by kwkbtr** [comment]
Fixed by #27.
