### ISSUE TITLE
Add support for spread=auto

### ISSUE THREAD

**Issue by frivoal** [vivliostyle/vivliostyle-ui#14]
When the page size is fixed, spread=auto should be able to detect if there's room for 2 pages or not.

If the page size is auto, spread=auto should go in spread mode if the browser window is wider than it is tall, unless the documents's stylesheet has `@page {size: landscape}` (possibly with a size as well).

Should writing modes make a difference?

**Comment by kwkbtr** [comment]
I don't think writing modes make any difference.
Most Japanese books have landscape pages regardless of their writing modes.
Furthermore, books having spreads with upper and lower pages (i.e. top-to-bottom page progression) are not typical.

**Comment by kwkbtr** [comment]
A very simple implementation, which does not see the actual page size, was added by vivliostyle/vivliostyle.js#300 and #41.
More advanced implementation using the actual page size is yet to come.
