### ISSUE TITLE
add support for user styles

### ISSUE THREAD

**Issue by frivoal** [vivliostyle/vivliostyle-ui#22]
Either full blown user style sheets, or at least the kind of controls offered by most ebook readers:
- black-on-white vs white-on-black vs sepia
- Serif vs Sans serif
- font size (we already have this one in the top toolbar)

**Comment by MurakamiShinyu** [comment]
Implemented https://github.com/vivliostyle/vivliostyle-ui/pull/64 "User style parameter settings"
