### ISSUE TITLE
Change the page size selection UI

### ISSUE THREAD

**Issue by frivoal** [vivliostyle/vivliostyle-ui#29]
- Instead of radio buttons for chosing the size manually, which only work if there is no size preset in the document, and a checkbox to make them work if there is a size in the document. Having radio buttons that sometimes work and sometimes don't is confusing, and even if you're not confused, needing 4 clicks (open the menu, tick the check box, select a radio button, click apply) to change the page size isn't great. We should remove the checkbox, and instead add one more radio button, selected by default, called "Document default" or something like that. 
- there should be a URL parameter `&page-size=auto` `&page-size=A4%20Landscape` etc. When included, it overrides the document's @page rule, and when omitted, we use the document's @page rule
- When switching the UI's radio button about which page size should be used, we should update the url to change the &page-size parameter.
- The `&speard=true` argument should be syncrhonized with the UI checkbox as well.

**Comment by kwkbtr** [comment]
Agreed.
One clarification: when a page size other than "Document default" is selected, it is treated as a user stylesheet with `!important`, overriding a page size specified in the document, right?

**Comment by frivoal** [comment]
Yes. That's how it is working now when you click the "override" checkbox, right?

**Comment by kwkbtr** [comment]
> That's how it is working now when you click the "override" checkbox, right?

Right.

**Comment by kwkbtr** [comment]
> The &speard=true argument should be syncrhonized with the UI checkbox as well.

This is solved by #36.

**Comment by MurakamiShinyu** [comment]
Implemented: https://github.com/vivliostyle/vivliostyle-ui/pull/64 "User style parameter settings"
