### ISSUE TITLE
Hide or dim the previous / next page arrow when there's no previous / next page.

### ISSUE THREAD

**Issue by frivoal** [vivliostyle/vivliostyle-ui#31]
The content does not always make it obvious whether we are at the start / end of a document, so the UI should give a hint.
![See this illustration](https://cloud.githubusercontent.com/assets/113268/14371555/e8d1d31e-fd73-11e5-924b-1daac4586c44.png)

**Comment by MurakamiShinyu** [comment]
Done. https://github.com/vivliostyle/vivliostyle-ui/pull/56
