### ISSUE TITLE
Broken layout in an output PDF

### ISSUE THREAD

**Issue by hajimehoshi** [vivliostyle/vivliostyle-ui#81]
I used macOS Mojave version 10.14.6 (18G95).

The steps to reproduce this issue are:

1. Open https://vivliostyle.github.io/vivliostyle.js/viewer/vivliostyle-viewer.html#b=https://vivliostyle.github.io/vivliostyle_doc/ja/vivliostyle-user-group-vol1/index.html&renderAllPages=true&userStyle=data:,/*%3Cviewer%3E*/%0A/*%3C/viewer%3E*/%0A@page%7Bmarks:crop%20cross;bleed:3mm%7D on Chrome (Version 78.0.3904.70 (Official Build) (64-bit))
2. Try to output this as PDF (with background graphics on)
3. The output PDF layout was broken: [![Screenshot from Gyazo](https://gyazo.com/e2deafdbb467ee4985b20ff127f89169/raw)](https://gyazo.com/e2deafdbb467ee4985b20ff127f89169)

**Comment by MurakamiShinyu** [comment]
Duplicate with https://github.com/vivliostyle/vivliostyle.js/issues/547

**Comment by hajimehoshi** [comment]
Thanks!
